### ISSUE TITLE
Unable to run helm chart

### ISSUE THREAD

**Issue by sp-90** [mumoshu/prometheus-process-exporter#15]
getting Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "psp-process-exporter-prometheus-process-exporter" namespace: "" from "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "psp-process-exporter-prometheus-process-exporter" namespace: "" from "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
ensure CRDs are installed first]

please can some one help  with it

**Comment by naohiroo** [comment]
Got same error.
In kubernetes version >= 1.22, `rbac.authorization.k8s.io/v1` must be used instead of `rbac.authorization.k8s.io/v1beta1`.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122
